[platformio]
default_envs = crosspoint_h716
build_cache_dir = .cache

[crosspoint]
version = 1.5.0

[base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DEINK_DISPLAY_SINGLE_BUFFER_MODE=1
  -DDISABLE_FS_H_WARNING=1
  -DDESTRUCTOR_CLOSES_FILE=1
  -DXML_GE=0
  -DXML_CONTEXT_BYTES=1024
  -DNO_SIMD
  -std=gnu++2a
  -fno-exceptions
  -DFREEINK_DRIVER_FASTEPD=1
  -DUSE_UTF8_LONG_NAMES=1
  -DPNG_MAX_BUFFERED_PIXELS=16416
  -Wno-bidi-chars
  -O2
  -Wl,--wrap=panic_print_backtrace,--wrap=panic_abort,--wrap=bootloader_common_check_efuse_blk_validity

build_unflags =
  -std=gnu++11
  -std=gnu++14
  -std=gnu++17
  -std=c++11
  -std=c++14
  -std=c++17

board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = partitions.csv

extra_scripts =
  pre:scripts/patch_wolfssl.py
  pre:scripts/gen_i18n.py
  pre:scripts/git_branch.py
  pre:scripts/patch_jpegdec.py
  post:scripts/merge_bin.py

lib_deps =
  greiman/SdFat @ ^2.3.1
  bblanchon/ArduinoJson @ 7.4.2
  ricmoo/QRCode @ 0.0.1
  bitbank2/PNGdec @ 1.1.6
  https://github.com/bitbank2/JPEGDEC.git#86282979224c8a32fd51e091ed5a35b0c699a52b
  links2004/WebSockets @ 2.7.3
  wolfssl/Arduino-wolfSSL @ 5.7.2
  https://github.com/tonywestonuk/EPD_Painter.git

[env:crosspoint_h716]
extends = base
board_build.mcu = esp32s3
board_build.arduino.memory_type = dio_opi
build_flags =
  ${base.build_flags}
  -DFREEINK_DEVICE_LILYGO_H716=1
  -DCROSSPOINT_VERSION=\"${crosspoint.version}-h716\"
  -DENABLE_SERIAL_LOG
  -DLOG_LEVEL=2
  -DFREEINK_CAP_BLE_HID_HOST=1
  -DFREEINK_FB_PSRAM=1
lib_ignore = FreeInkDisplay, HalClockSim, BLE
lib_deps =
  ${base.lib_deps}
  m5stack/M5GFX @ 0.2.20
  h2zero/NimBLE-Arduino @ ^2.3.8
  BoardConfig=symlink://freeink-sdk/libs/hardware/BoardConfig
  InputManager=symlink://freeink-sdk/libs/hardware/InputManager
  EInkDisplay=symlink://freeink-sdk/libs/display/FreeInkDisplay
  SDCardManager=symlink://freeink-sdk/libs/hardware/SDCardManager
  XteinkDetect=symlink://freeink-sdk/libs/hardware/XteinkDetect
  PowerManager=symlink://freeink-sdk/libs/hardware/PowerManager
  BatteryMonitor=symlink://freeink-sdk/libs/hardware/BatteryMonitor
  Rtc=symlink://freeink-sdk/libs/hardware/Rtc
  Imu=symlink://freeink-sdk/libs/hardware/Imu
  SecureNet=symlink://freeink-sdk/libs/network/SecureNet
  FreeInkUI=symlink://freeink-sdk/libs/ui/FreeInkUI
  Icons=symlink://freeink-sdk/libs/assets/Icons
  BoardT5S3=symlink://freeink-sdk/libs/hardware/BoardT5S3
