#pragma once

#include <string>
#include <vector>

class GfxRenderer;
struct Rect;

namespace LibraryCache {

struct Entry {
  std::string path;
  std::string title;
  std::string author;
};

// Returns the expected cover thumbnail path for a book (still used for legacy
// thumbnails generated by the Home screen reader, but the library itself no
// longer generates covers).
std::string thumbPathFor(const std::string& path, int coverW, int coverH);

// Index persistence (JSON at /.crosspoint/library_index.json)
bool exists();
bool load(std::vector<Entry>& out);
bool save(const std::vector<Entry>& entries);
void invalidate();
bool removeBook(const std::string& path);

// SD scanning
bool sync(std::vector<Entry>& out, const char* rootDir = "/", int maxBooks = 1000);
bool scan(GfxRenderer& renderer, const Rect& popupRect, std::vector<Entry>& out,
          const char* rootDir = "/", int maxBooks = 1000);

// Cover generation has been removed from the library path to avoid
// memory pressure, corrupt-ZIP crashes, and O(n) heap fragmentation.
// The library will render a placeholder icon + book title for every entry.
// Covers generated by the Home screen reader (Epub::generateThumbBmp) are
// still picked up by drawTileContent() if they exist on disk.

}  // namespace LibraryCache
